src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Account__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Accounts</relationshipLabel>
        <relationshipName>Customer_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CustomerAndAccountController.cls
public class CustomerAndAccountController{

    public Account account { get; private set; }

    public Customer_Account__c customer {get; private set; }

    Account acc = [SELECT Name, Phone, Email__c FROM Account WHERE Name = :'test1'];

    public CustomerAndAccountController() {
        Id id = ApexPages.currentPage().getParameters().get('id');
        account = (id == null) ? new Account() : 
                [SELECT Name, Phone, Email__c FROM Account WHERE Id = :id];
        customer = (id == null) ? new Customer_Account__c(Customer__c = acc.Id) :
                [select Name, Balance__c from Customer_Account__c where Id = :id];
    }

    public PageReference saveCustomer() {
        try {
            insert (account);
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
//        PageReference redirectSuccess = new ApexPages.StandardController(Account).view();
//        return (redirectSuccess);
        return null;
    }
    public PageReference saveCustomerAccount() {
        try {
            insert (customer);
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
//        PageReference redirectSuccess = new ApexPages.StandardController(Account).view();
//        return (redirectSuccess);
        return null;
    }


//    public PageReference save() {
//        try {
//            insert (account);
//        } catch(System.DMLException e) {
//            ApexPages.addMessages(e);
//            return null;
//        }
//        //  After successful Save, navigate to the default view page
//        PageReference redirectSuccess = new ApexPages.StandardController(Account).view();
//        return (redirectSuccess);
//    }

}