src/objects/Customer_Account__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Accounts</relationshipLabel>
        <relationshipName>Customer_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateCustomerAccountWithCustomer.cls
public  with sharing class CreateCustomerAccountWithCustomer {

        @AuraEnabled
    public static Account saveCustomer(Account account) {
        upsert account;
        return account;
    }
    
        @AuraEnabled
    public static Id saveCustomerAccount(Customer_Account__c customerAccount) {
        Account acc = [select Name, Id from Account where Name = :'Org1'];
        Customer_Account__c objCustomerAccount = new Customer_Account__c(
        	Customer__c = '0016F00002OPLbCQAX',
            Balance__c = customerAccount.Balance__c,
            Name = customerAccount.Name
        );
        upsert objCustomerAccount;
        return objCustomerAccount.Id;
    }
}