src/objects/Customer_Account__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Customer Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Customer_Account__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountChangeTriggerHandler.cls
/**
 * Created by t.shkoda on 16.07.18.
 */

public class AccountChangeTriggerHandler extends TriggerHandler{


    protected override void afterInsert() {
        UpdateBalance();
    }

    private void UpdateBalance(){
        Set<Id> allInsertedIds = trigger.newMap.keySet();
        Transaction__c CustomerAccount = [SELECT Customer_Account__c, Transaction_Amount__c From Transaction__c where Id =: allInsertedIds];
        Customer_Account__c objAccount = [Select Id, Balance__c, Current_Balance__c From Customer_Account__c where Id =: CustomerAccount.Customer_Account__c];

        objAccount.Current_Balance__c = objAccount.Current_Balance__c + CustomerAccount.Transaction_Amount__c;

        update objAccount;

    }

}